images/turingpi2-alpine: update kernel config and fix unwanted polution of rootfs from otg init script

diff --git a/images/turingpi2-alpine.Dockerfile.d/273_seed_config.sh.d/etc/init.d/otg b/images/turingpi2-alpine.Dockerfile.d/273_seed_config.sh.d/etc/init.d/otg
--- a/images/turingpi2-alpine.Dockerfile.d/273_seed_config.sh.d/etc/init.d/otg
+++ b/images/turingpi2-alpine.Dockerfile.d/273_seed_config.sh.d/etc/init.d/otg
@@ -34,19 +34,22 @@ update_udc() {
 setup_configuration() {
     mount -t configfs none /sys/kernel/config > /dev/null 2>&1
     mkdir -p $usb_gadget
-    cd $usb_gadget
-
-    echo "0x08DE" > idVendor
-    echo "0x1234" > idProduct
-    mkdir -p strings/0x409
-    echo "$serial" > strings/0x409/serialnumber
-    echo "Turing Machines" > strings/0x409/manufacturer
-    echo "$model" > strings/0x409/product
-    mkdir -p functions/acm.usb0
-    mkdir -p configs/c.1
-    mkdir -p configs/c.1/strings/0x409
-    echo "$name" > configs/c.1/strings/0x409/configuration
-    ln -s functions/acm.usb0 configs/c.1
+    if cd $usb_gadget; then
+      echo "0x08DE" > idVendor
+      echo "0x1234" > idProduct
+      mkdir -p strings/0x409
+      echo "$serial" > strings/0x409/serialnumber
+      echo "Turing Machines" > strings/0x409/manufacturer
+      echo "$model" > strings/0x409/product
+      mkdir -p functions/acm.usb0
+      mkdir -p configs/c.1
+      mkdir -p configs/c.1/strings/0x409
+      echo "$name" > configs/c.1/strings/0x409/configuration
+      ln -s functions/acm.usb0 configs/c.1
+    else # failed to init USB OTG
+      echo "FAIL"
+      exit 1
+    fi
 }
 
 start() {
