recipes/alpine/SBC+openrc-init+overlay: OS | MMC: add free space check and adapt armbianEnv.txt on platforms which need it

diff --git a/recipes/alpine/SBC+openrc-init+overlay/190_overlay+openrc-init.sh.d/usr/local/bin/OS b/recipes/alpine/SBC+openrc-init+overlay/190_overlay+openrc-init.sh.d/usr/local/bin/OS
--- a/recipes/alpine/SBC+openrc-init+overlay/190_overlay+openrc-init.sh.d/usr/local/bin/OS
+++ b/recipes/alpine/SBC+openrc-init+overlay/190_overlay+openrc-init.sh.d/usr/local/bin/OS
@@ -45,6 +45,8 @@ update_root() {
   RUNNING_VERSION="$( cat /rom/boot/build.meta )"
   RUNNING="/rom/mnt/ROOTFS.$RUNNING_VERSION"
 
+  RO_FREE_kb="$( df -hk /rom/mnt | awk '$0 ~ "^/" { print $4 }' )"
+
   NEXT_VERSION=$( cat "$MNT/boot/build.meta" )
   NEXT="$RO/ROOTFS.$NEXT_VERSION"
   NEXT_SIZE_kb=$( sum=0; du -xshkL "$SQFS" "$MNT/boot" "$MNT/sbin/busybox.static" | { while read i _; do sum=$(( sum + i)); done; echo $sum ; } )
@@ -58,11 +60,15 @@ update_root() {
   echo "I: running version: $RUNNING_VERSION"
   echo "I: new version    : $NEXT_VERSION"
   echo
-  echo "I: needed size: $NEXT_SIZE_kb KB"
+  echo "I: free size:   $RO_FREE_kb"
+  echo "I: needed size: $NEXT_SIZE_kb KB (SQFS + /boot)"
 
-  # TODO: size check
+  if [ $NEXT_SIZE_kb -gt $RO_FREE_kb ]; then
+    echo "E: too less space on device, ABORT" 1>&2
+    exit 1
+  fi
 
-  # TODO: ensuring structure in /rom/mnt
+  # TODO: check & ensuring structure in /rom/mnt
   #        * /dev /proc /sbin
   #        * /sbin/busybox           (static)
   #        * /sbin/init
@@ -84,6 +90,13 @@ update_root() {
   echo "I: updating next boot"
   rm -f "$RO/CURRENT"
   ln -s "${NEXT##*/}" "$RO/CURRENT"
+
+  if [ -f "$NEXT/boot/armbianEnv.txt" ]; then
+    RO_UUID="$(findmnt -o UUID -n /rom/mnt)"
+    ROOT_CMDLINE="UUID=$RO_UUID"
+    echo "I: found /boot/armbianEnv.txt, preparing with UUID=$RO_UUID"
+    sed -i -r -e "/rootdev=/ s/=.*$/=$ROOT_CMDLINE/" "$NEXT/boot/armbianEnv.txt"
+  fi
 
   NEXT="$(readlink -f /rom/mnt/CURRENT)"
   echo "I: --> next boot:     $NEXT"
